import os


DEFAULT_ROWS = 5
DEFAULT_COLS = 5
DEFAULT_CANDIDATES_PER_SLOT = 15
DEFAULT_BRANCH_BUDGETS = [0, 2, 4, 6, 8, 10]
DEFAULT_HIDDEN_SLOTS = [1, 3, 5, 7, 9, 13, 17]
DEFAULT_MAX_RETRIES = 160
DEFAULT_CANDIDATE_RESAMPLE_RETRIES = 12
DEFAULT_SLOT_CANDIDATE_RETRIES = 4000
DEFAULT_OPEN_VALID_PREFERENCE_TRIES = [30, 50, 70]
DEFAULT_OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "data")
